/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Render.JComboBoxRender;
import java.util.Hashtable;
import javax.swing.ImageIcon;
import java.lang.Math;
import webScraper.Scraper;

/**
 *
 * @author Dagoberto
 */
public class principal extends javax.swing.JFrame {
    
    
    Hashtable<Object, ImageIcon> mElementos;
    int width = 40;
    int height = 30;
    
    
    private String logo_usa = "/Icons/USA.png";
    private String logo_nicaragua = "/Icons/Nicaragua.png";
    private String logo_euro = "/Icons/Euro.png";
    private String logo_peru = "/Icons/peru.png";
    

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        mElementos = new Hashtable<>();
        initCombo();
    }
    
    public void initCombo() {
        agregarElemento("USD", getIcono(logo_usa));
        agregarElemento("NIO", getIcono(logo_nicaragua));
        agregarElemento("EUR", getIcono(logo_euro));
        agregarElemento("PEN", getIcono(logo_peru));

        comboboxFrom.addItem("USD");
        comboboxFrom.addItem("NIO");
        comboboxFrom.addItem("EUR");
        comboboxFrom.addItem("PEN");
        
        comboboxTo.addItem("USD");
        comboboxTo.addItem("NIO");
        comboboxTo.addItem("EUR");
        comboboxTo.addItem("PEN");

        JComboBoxRender mJComboBoxRender = new JComboBoxRender(mElementos);
        comboboxFrom.setRenderer(mJComboBoxRender);
        comboboxTo.setRenderer(mJComboBoxRender);
    }
    
    public void agregarElemento(String akey, ImageIcon aImageIcon) {
        mElementos.put(akey, aImageIcon);
    }

    public ImageIcon getIcono(String path) {
        return new ImageIcon(new ImageIcon(getClass().getResource(path)).getImage()
                .getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        editTextCantidad = new javax.swing.JTextField();
        labelDe = new javax.swing.JLabel();
        labelA = new javax.swing.JLabel();
        comboboxTo = new javax.swing.JComboBox<>();
        comboboxFrom = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        labelTextConversion = new javax.swing.JLabel();
        botonRealizarConversion = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Conversor de Moneda");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jLabel2.setText("Ingresar Cantidad:");

        labelDe.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        labelDe.setText("De:");

        labelA.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        labelA.setText("A:");

        comboboxTo.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        comboboxFrom.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        comboboxFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxFromActionPerformed(evt);
            }
        });

        labelTextConversion.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        labelTextConversion.setText("Esperando Conversion ...");

        botonRealizarConversion.setBackground(new java.awt.Color(103, 90, 254));
        botonRealizarConversion.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        botonRealizarConversion.setForeground(new java.awt.Color(255, 255, 255));
        botonRealizarConversion.setText("Realizar Cambio de moneda");
        botonRealizarConversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRealizarConversionActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(">>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(labelDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(comboboxFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(76, 76, 76))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(comboboxTo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(editTextCantidad)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelTextConversion, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(botonRealizarConversion)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editTextCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDe)
                    .addComponent(labelA))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(comboboxFrom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboboxTo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelTextConversion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(botonRealizarConversion, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRealizarConversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRealizarConversionActionPerformed
        
        Scraper tablaMoneda = new Scraper();

        //obteber las monedas a utilizar de los comboBoxes
        String monedaEntrada = comboboxFrom.getSelectedItem().toString();
        String monedaSalida = comboboxTo.getSelectedItem().toString();
        
        float mEntrada;
        float mSalida;
        
        float cantidad_a_convertir = Float.parseFloat(editTextCantidad.getText());
        String resultado;
        
        //extraemos la conversion de cada moneda a dolar
        Float ConversionDolardeMonedaEntrante = tablaMoneda.extraerDatosMoneda(monedaEntrada);
        Float ConversionDolardeMonedaSaliente = tablaMoneda.extraerDatosMoneda(monedaSalida);
        
        if(monedaEntrada == "NIO"){
            mEntrada = cantidad_a_convertir/ ConversionDolardeMonedaEntrante;
        }else if(monedaEntrada == "EUR"){
            mEntrada = cantidad_a_convertir/ ConversionDolardeMonedaEntrante;
        }else if(monedaEntrada == "PEN"){
            mEntrada = cantidad_a_convertir/ ConversionDolardeMonedaEntrante;
        }else{
            mEntrada = cantidad_a_convertir/ ConversionDolardeMonedaEntrante; 
        }
        
        // Realizar la conversión
        if(monedaSalida == "NIO"){
            mSalida = ConversionDolardeMonedaSaliente* mEntrada;
        }else if(monedaSalida == "EUR"){
            mSalida = ConversionDolardeMonedaSaliente* mEntrada;
        }else if(monedaSalida == "PEN"){
            mSalida = ConversionDolardeMonedaSaliente* mEntrada;
        }else{
            mSalida = ConversionDolardeMonedaSaliente* mEntrada; 
        }

        //calculo para que redondear cualquier resultado a 2 decimales
        double digitoResultado = Math.floor(mSalida * 100) / 100;
        
        //conversion del resultado a String
        String res = Double.toString(digitoResultado);
        
        //String con el resultado final
        resultado = cantidad_a_convertir + monedaEntrada + " = " + res + monedaSalida;
        
        labelTextConversion.setText(resultado);
    }//GEN-LAST:event_botonRealizarConversionActionPerformed

    private void comboboxFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxFromActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRealizarConversion;
    private javax.swing.JComboBox<String> comboboxFrom;
    private javax.swing.JComboBox<String> comboboxTo;
    private javax.swing.JTextField editTextCantidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel labelA;
    private javax.swing.JLabel labelDe;
    private javax.swing.JLabel labelTextConversion;
    // End of variables declaration//GEN-END:variables

    
}
